version: '3'

services:
  dog:
    image: nginx
    volumes:
      - ./dog:/usr/share/nginx/html
    ports:
      - 3000:80

  cat:
    image: nginx
    volumes:
      - ./cat:/usr/share/nginx/html
    ports:
      - 3002:80

  front:
    image: nginx
    volumes:
      - ./front/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:8000
